// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFnJCS39d6VgB--5tLpB6bRNGdVkiBKSM',
    appId: '1:716700607349:web:b9035f7f6d5f3d4f90293c',
    messagingSenderId: '716700607349',
    projectId: 'agendaria-aa948',
    authDomain: 'agendaria-aa948.firebaseapp.com',
    storageBucket: 'agendaria-aa948.firebasestorage.app',
    measurementId: 'G-CDR3M3KZSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1hdUhdDdv1Nhs7lbj-7CF59Hu1ewdwns',
    appId: '1:716700607349:android:4ab758fa71b3f77590293c',
    messagingSenderId: '716700607349',
    projectId: 'agendaria-aa948',
    storageBucket: 'agendaria-aa948.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6HBT3EqpsFU5RkZNnU7LBHdxvocZwFjA',
    appId: '1:716700607349:ios:7e938bfcfbeb249790293c',
    messagingSenderId: '716700607349',
    projectId: 'agendaria-aa948',
    storageBucket: 'agendaria-aa948.firebasestorage.app',
    iosBundleId: 'com.example.agendaria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6HBT3EqpsFU5RkZNnU7LBHdxvocZwFjA',
    appId: '1:716700607349:ios:7e938bfcfbeb249790293c',
    messagingSenderId: '716700607349',
    projectId: 'agendaria-aa948',
    storageBucket: 'agendaria-aa948.firebasestorage.app',
    iosBundleId: 'com.example.agendaria',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFnJCS39d6VgB--5tLpB6bRNGdVkiBKSM',
    appId: '1:716700607349:web:790786d02a220e8190293c',
    messagingSenderId: '716700607349',
    projectId: 'agendaria-aa948',
    authDomain: 'agendaria-aa948.firebaseapp.com',
    storageBucket: 'agendaria-aa948.firebasestorage.app',
    measurementId: 'G-49PENE6M11',
  );
}
